### ISSUE TITLE
[Bug] Not ripping paid content

### ISSUE THREAD

**Issue by Telandriq** [excludedBittern8/ofscraper#1]
When using the script, I did get it to work to rip a user's profile but when it came to paid content, the image below shows it doesn't rip. 

![image](https://user-images.githubusercontent.com/61485418/228724159-9729e18e-35c6-4cd5-a049-acfb3db206a2.png)

**Comment by excludedBittern8** [comment]
Also it should print the username right away. With the  latest changes. You can see how not doing so is confusing it finishes one model and is scraping the next but that is clear until later
