### ISSUE TITLE
Setting for auto picking

### ISSUE THREAD

**Issue by ctrlcmdshft** [excludedBittern8/ofscraper#10]
Options in config to pick all choices as needed

**Comment by excludedBittern8** [comment]
You can pick any desired choices through the commandline

https://github.com/excludedBittern8/ofscraper/wiki/command-line-args

I think many people are just running

```
ofscraper
```

That is really just a convenience feature
Personally if I am running the script I usually do it with args

**Comment by ctrlcmdshft** [comment]
Good to know TY
