### ISSUE TITLE
Editing AUTH from CMD not working

### ISSUE THREAD

**Issue by thepetcow** [excludedBittern8/ofscraper#2]
When attempting to edit the AUTH.JSON from the CMD (using the script), it asks:

```
? What would you like to do? Edit `auth.json` file
? Enter the path to the directory that contains your database files: D:\Scraper\Database
? Enter that model's username: 
```
It does not matter what you type into the 'model's username', the script will crash.

Can still modify it manually though, so not really a high priority issue, just a strange bug.

**Comment by ctrlcmdshft** [comment]
i got passed this part by choosing edit profile and entering auth info when asked and proceeded to enter asked info. I can see the models in the list when choosing that option but wont download any media. show all zeros

**Comment by thepetcow** [comment]
> i got passed this part by choosing edit profile and entering auth info when asked and proceeded to enter asked info. I can see the models in the list when choosing that option but wont download any media. show all zeros

Same. I'm able to see my model list, but everything is zero even when selecting all options to scrape. 

It's a new script, lets give it time. Even if it's not downloading anything, still working a hell of a lot better than the other one! At least this one loads...

**Comment by TMD20** [comment]
The database transfer feature might not work. It was built for a older version of dc script.
I'm working on adding meta data, and a DB using the same DB files

**Comment by excludedBittern8** [comment]
For now version 1.51 should force a proper auth file. 

I haven't encounter the printing zero error.
If you could take a screenshot of program running that would be very helpful

alternatively I just need to know what command your  running with. 
Also what options your picking in the menu.
and I think seeing what model your attempting to download from would be helpful. 
If a subscription has expired for example, then you can only scrape messages and paid content.

**Comment by excludedBittern8** [comment]
![image](https://user-images.githubusercontent.com/67020411/230509986-d7ded9ab-6541-4527-9474-d6c39baee928.png)

In this case if you select enter field manually, then it will be prefilled with your previous values
