### ISSUE TITLE
Naming the downloads

### ISSUE THREAD

**Issue by ctrlcmdshft** [excludedBittern8/ofscraper#4]
Any plans on adding an option to name the downloads "{date} - {text}" date being date posted and name being the post text.

**Comment by TMD20** [comment]
I'm hoping to have this feature be part of the next major update 

Which would also include support for metadata.

**Comment by excludedBittern8** [comment]
I plan on added this feature in next update or soon after

It should be coming this week

**Comment by excludedBittern8** [comment]
This feature has been implemented
https://github.com/excludedBittern8/ofscraper/wiki/Customizing-save-path
